"""z3schedule

Revision ID: 755de4c1e083
Revises: 
Create Date: 2022-06-21 11:34:38.269158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755de4c1e083'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('z3_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('z3_schedule')
    # ### end Alembic commands ###
